//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Application {
	
	
	public partial class ZhuangXShenQi {
		
		protected System.Web.UI.HtmlControls.HtmlImage img;
		
		protected System.Web.UI.HtmlControls.HtmlImage imgEmpty;
		
		protected System.Web.UI.HtmlControls.HtmlForm form1;
		
		protected System.Web.UI.WebControls.TextBox name;
		
		protected System.Web.UI.WebControls.TextBox departure;
		
		protected System.Web.UI.WebControls.TextBox arrival;
		
		protected System.Web.UI.WebControls.TextBox date;
		
		protected System.Web.UI.WebControls.Label lblName;
		
		protected System.Web.UI.WebControls.Label lblDeparture;
		
		protected System.Web.UI.WebControls.Label lblArrival;
		
		protected System.Web.UI.WebControls.Label lblFlightNumber;
		
		protected System.Web.UI.WebControls.Label lblDate;
		
		protected System.Web.UI.WebControls.Label lblName1;
		
		protected System.Web.UI.WebControls.Label lblDeparture1;
		
		protected System.Web.UI.WebControls.Label lblArrival1;
		
		protected System.Web.UI.WebControls.Label lblFlightNumber1;
		
		protected System.Web.UI.WebControls.Label lblDate1;
		
		protected System.Web.UI.WebControls.Button Button2;
	}
}
